version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: chat_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
      MYSQL_USER: chat
      MYSQL_PASSWORD: chatpass
    ports:
      - "3307:3306" # ホスト3307→コンテナ3306（3306使用中対策）
    volumes:
      - mysql_data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

  backend:
    build:
      context: ./backend
    container_name: chat_backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: chat_app
      DB_USERNAME: chat
      DB_PASSWORD: chatpass
      SANCTUM_STATEFUL_DOMAINS: localhost:5173
      SESSION_DOMAIN: localhost
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: ["sh","/var/www/html/docker/entrypoint.sh"]  # ← これを追加

  nginx:
    image: nginx:alpine
    container_name: chat_nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    build:
      context: ./frontend
    container_name: chat_frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      VITE_API_BASE: http://localhost:8080/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm","run","dev","--","--host"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chat_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: chat
      PMA_PASSWORD: chatpass
      UPLOAD_LIMIT: 64M
    ports:
      - "8081:80"

volumes:
  mysql_data: